### ISSUE TITLE
[Upstream] `posix_spawn_file_actions_addfchdir_np()` issue in iOS and Mac Catalyst builds

### ISSUE THREAD

**Issue by birdofpreyru** [birdofpreyru/lighttpd1.4#2]
Hey @gstrauss , let's coninue [the discussion](https://github.com/lighttpd/lighttpd1.4/commit/fd142a53ebab66e6d2057a84485a1812499e9410#r113823049) here.

> ??? in case of what ??? what does that mean ???

I mean, in case you consider it is worth doing anything about it in upstream codebase (as iOS is not a high-priority target for you, and I am not 100% sure it is not some mistake in my setup causing CMake finding this funciton).

> MacOS Catalyst (whatever that is)

[Mac Catalyst](https://developer.apple.com/mac-catalyst/) is an Apple's solution for building iOS apps for Mac. 

> if you provide the preprocessor macros for version identification when it works (or iOS platform identification to disable, i.e. TARGET_OS_IPHONE)

I haven't tried to solve it with preprocessor macros, but I guess you are right, `#if !TARGET_OS_IPHONE` should do the trick, as [it seems to cover both iOS and Mac Catalyst targets](https://github.com/xybp888/iOS-SDKs/blob/f4fc87b8fd12c1e7902b72b78b65878a61545bd2/iPhoneOS13.0.sdk/usr/include/TargetConditionals.h#L80-L88).

For me I fixed it by modifying CMakeLists.txt, but I guess `CMAKE_SYSTEM_NAME MATCHES "Darwin"` piece will also remove it for proper Mac OS builds, not something you will like:
https://github.com/birdofpreyru/lighttpd1.4/blob/3d68bc256cb4134fc771042371339066bf28f4c4/src/CMakeLists.txt#L231-L234

> Is lighttpd failing during compilation and linking?

It fails during the compilation and linking.

**Comment by gstrauss** [comment]
> For me I fixed it by modifying CMakeLists.txt, but I guess CMAKE_SYSTEM_NAME MATCHES "Darwin" piece will also remove it for proper Mac OS builds, not something you will like:

Also, lighttpd supports multiple build systems besides CMake, and changes should generally be applied consistently.

This is what I did:

https://git.lighttpd.net/lighttpd/lighttpd1.4/commit/661905adf42f6133eb70bd197a8debce04d8a250

**Comment by birdofpreyru** [comment]
Tested, works as intended for me :)
